services:
  clover-sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clover-sim
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/anaju/Documentos/clover-simulator:/root/catkin_ws
    devices:
      - /dev/dri:/dev/dri
    tty: true
    stdin_open: true
